artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/polaternez/SampleDatasets/raw/master/cyberbullying_tweets_v2.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_cleaning:
  root_dir: artifacts/data_cleaning
  data_path: artifacts/data_ingestion/cyberbullying_tweets_v2.csv

data_transformation:
  root_dir: artifacts/data_transformation
  cleaned_data_path: artifacts/data_cleaning/cleaned_tweets.csv
  preprocessor_name: preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  model_name: model.pkl
